version: '3'

services:
  zookeeper:
    image: token/zookeeper:080222
    container_name: zookeeper
    ports:
      - "2181:2181"
#    command: tail -f /dev/null
  kafka:
    image: token/kafka:080222
    container_name: kafka
    ports:
      - "9092:9092"
 #   command: tail -f /dev/null
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
