apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: producer-consumer-client-user
  namespace: tls-kafka
  labels:
    strimzi.io/cluster: kuberakskafka
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: my-topic
          patternType: literal
        operation: All
  # ...
