apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-user
  namespace: tls-kafka
spec:
  kafka:
    authorization:
      type: simple
      superUsers:
        - CN=strimzi-kafka-admin
    # ...
