apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-tls-cluster
spec:
  kafka:
    version: 2.2.1
    replicas: 3
    listeners:
    - name: tls
      port: 9093
      type: internal
      tls: true
      authentication:
        type: tls
    config:
      log.message.format.version: 2.2
      ssl.client.auth: required
    storage:
      volumes:
      - type: persistent-claim
        size: 64Gi
        class: managed-premium
        id: 0
      type: jbod
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 32Gi
      class: managed-premium
  entityOperator:
    topicOperator: {}
    userOperator: {}
