version: '3'

services:
  zookeeper:
    image: token/zookeeper:120222
    container_name: zookeeper
    networks:
      - kafka_network
#    ports:
#      - "2181:2181"
  kafka:
    image: token/kafka:120222
    container_name: kafka
    networks:
      - kafka_network
#    ports:
#      - "29092:29092"
    environment:
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://0.0.0.0:29092,INTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "topicDiscMessage:1:1"

networks:
  kafka_network:
    name: kafka_token_discourse_net
#      KAFKA_ADVERTISED_HOST_NAME: localhost
